# Generated by Django 5.2.18 on 2026-10-06 14:46

import apps.accounts.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=160, unique=True)),
                ('country', models.CharField(choices=[('PK', 'Pakistan'), ('IN', 'India')], default='PK', max_length=2)),
                ('timezone', models.CharField(choices=[('Asia/Karachi', 'Pakistan time (PKT)'), ('Asia/Kolkata', 'India time (IST)')], default='Asia/Karachi', max_length=50)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('appointment_reminder_days', models.PositiveSmallIntegerField(default=1, help_text='Remind patients this many days before an appointment.')),
                ('followup_reminder_days', models.PositiveSmallIntegerField(default=2, help_text='Remind patients this many days before a follow-up check-up is due.')),
                ('overdue_grace_days', models.PositiveSmallIntegerField(default=3, help_text='Flag a follow-up as overdue this many days after it was due.')),
                ('default_appointment_minutes', models.PositiveSmallIntegerField(default=15)),
                ('prescription_header', models.TextField(blank=True, help_text='Extra lines under the clinic name, e.g. clinic timings.')),
                ('prescription_footer', models.TextField(blank=True)),
                ('patient_counter', models.PositiveIntegerField(default=0, editable=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('full_name', models.CharField(max_length=150)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'ordering': ['full_name'],
            },
            managers=[
                ('objects', apps.accounts.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Clinic owner'), ('doctor', 'Doctor'), ('receptionist', 'Receptionist')], default='receptionist', max_length=20)),
                ('title', models.CharField(blank=True, default='', help_text='e.g. "Dr."', max_length=20)),
                ('qualifications', models.CharField(blank=True, help_text='e.g. MBBS, FCPS (Medicine)', max_length=150)),
                ('registration_number', models.CharField(blank=True, help_text='PMDC / NMC registration number', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='accounts.clinic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['clinic', 'user__full_name'],
                'constraints': [models.UniqueConstraint(fields=('user', 'clinic'), name='unique_membership_per_clinic')],
            },
        ),
    ]
