# Generated by Django 5.2.18 on 2026-10-07 06:04

import django.utils.timezone
from django.db import migrations, models
from django.db.models import F


def accept_existing_memberships(apps, schema_editor):
    """Everyone already on a staff list joined before invitations existed: they count as accepted."""
    Membership = apps.get_model("accounts", "Membership")
    Membership.objects.update(accepted_at=F("created_at"))


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='accepted_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, help_text='Empty while an invitation is waiting.', null=True),
        ),
        migrations.AddField(
            model_name='membership',
            name='invite_token',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=64),
        ),
        migrations.AddField(
            model_name='membership',
            name='invited_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='must_change_password',
            field=models.BooleanField(default=False, help_text='Set when a clinic owner chose the password. Cleared when they change it themselves.'),
        ),
        migrations.RunPython(accept_existing_memberships, migrations.RunPython.noop),
    ]
