# Generated by Django 5.2.18 on 2026-10-07 06:29

import django.core.validators
from django.db import migrations, models


def grace_of_zero_means_one_day(apps, schema_editor):
    """A grace of 0 always behaved as "the day after" (1); store it that way so the form accepts it."""
    Clinic = apps.get_model("accounts", "Clinic")
    Clinic.objects.filter(overdue_grace_days=0).update(overdue_grace_days=1)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_invitations_and_password_change'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='prescription_pad_space',
            field=models.PositiveSmallIntegerField(choices=[(0, 'No: print our letterhead'), (30, 'Yes: leave 3 cm blank'), (40, 'Yes: leave 4 cm blank'), (50, 'Yes: leave 5 cm blank'), (60, 'Yes: leave 6 cm blank')], default=0, help_text='For pads that already have your letterhead printed on them.'),
        ),
        migrations.AddField(
            model_name='clinic',
            name='prescription_paper',
            field=models.CharField(choices=[('a5', 'A5 (half sheet)'), ('a4', 'A4 (full sheet)')], default='a5', max_length=2),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='overdue_grace_days',
            field=models.PositiveSmallIntegerField(default=3, help_text='Flag a follow-up as overdue this many days after it was due (1 = the day after).', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.RunPython(grace_of_zero_means_one_day, migrations.RunPython.noop),
    ]
