# Generated by Django 5.2.18 on 2026-10-06 14:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('appointments', '0001_initial'),
        ('clinical', '0001_initial'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('appointment', 'Appointment reminder'), ('follow_up', 'Follow-up due'), ('overdue', 'Missed follow-up'), ('custom', 'Custom message')], max_length=20)),
                ('language', models.CharField(default='en', max_length=10)),
                ('body', models.TextField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_templates', to='accounts.clinic')),
            ],
            options={
                'ordering': ['kind'],
                'constraints': [models.UniqueConstraint(fields=('clinic', 'kind', 'language'), name='one_template_per_kind_language')],
            },
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('appointment', 'Appointment reminder'), ('follow_up', 'Follow-up due'), ('overdue', 'Missed follow-up'), ('custom', 'Custom message')], max_length=20)),
                ('due_date', models.DateField(help_text='Day the reminder should go out')),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'To send'), ('sent', 'Sent'), ('skipped', 'Skipped')], default='pending', max_length=20)),
                ('channel', models.CharField(choices=[('whatsapp_link', 'WhatsApp (one tap)'), ('whatsapp_api', 'WhatsApp (automatic)'), ('sms', 'SMS')], default='whatsapp_link', max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='appointments.appointment')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='accounts.clinic')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='patients.patient')),
                ('sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('visit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='clinical.visit')),
            ],
            options={
                'ordering': ['due_date', 'pk'],
                'indexes': [models.Index(fields=['clinic', 'status', 'due_date'], name='reminders_r_clinic__2b7ba8_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('appointment__isnull', False)), fields=('kind', 'appointment'), name='one_reminder_per_kind_per_appointment'), models.UniqueConstraint(condition=models.Q(('visit__isnull', False)), fields=('kind', 'visit'), name='one_reminder_per_kind_per_visit')],
            },
        ),
    ]
