# Generated by Django 5.2.18 on 2026-10-07 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='skip_reason',
            field=models.CharField(blank=True, choices=[('staff', 'Skipped by staff'), ('system', 'No longer needed')], max_length=10),
        ),
    ]
