{% autoescape off %}/* Clinic Records service worker: makes the app installable and shows a friendly page when offline.
 *
 * PRIVACY RULE: this worker NEVER caches HTML pages or JSON responses. They contain patient
 * data, and a shared clinic computer or a staff member's phone must not keep copies of it.
 * Only the design files (CSS, JS, icons) and the offline page (no patient data) are stored.
 *
 * Generated by apps/core/views.py (service_worker). The cache name changes whenever one of
 * the cached files changes, and old caches are deleted when the new worker takes over.
 */
"use strict";

const CACHE_NAME = {{ cache_name }};
const OFFLINE_URL = {{ offline_url }};
const PRECACHE_URLS = {{ precache_urls }};
const PRECACHE_PATHS = new Set(PRECACHE_URLS);

self.addEventListener("install", (event) => {
  event.waitUntil(
    caches
      .open(CACHE_NAME)
      .then((cache) =>
        cache.addAll(
          // credentials "omit": fetched as a signed-out visitor, so nothing personal ends up in the cache.
          PRECACHE_URLS.map((url) => new Request(url, { credentials: "omit", cache: "reload" }))
        )
      )
      .then(() => self.skipWaiting())
  );
});

self.addEventListener("activate", (event) => {
  event.waitUntil(
    caches
      .keys()
      .then((names) => Promise.all(names.filter((name) => name !== CACHE_NAME).map((name) => caches.delete(name))))
      .then(() => self.clients.claim())
  );
});

self.addEventListener("fetch", (event) => {
  const request = event.request;
  if (request.method !== "GET") return; // form posts always go straight to the server

  const url = new URL(request.url);
  if (url.origin !== self.location.origin) return;

  if (request.mode === "navigate") {
    // Pages: network only, never cached. If there is no connection, show the offline page.
    event.respondWith(fetch(request).catch(() => caches.match(OFFLINE_URL)));
    return;
  }

  if (PRECACHE_PATHS.has(url.pathname)) {
    // Design files: from the cache first (they are refreshed when the cache name changes).
    event.respondWith(caches.match(request, { ignoreSearch: true }).then((cached) => cached || fetch(request)));
  }
  // Anything else (search results, lab files, other scripts) goes to the network as normal and is not stored.
});
{% endautoescape %}
