# Generated by Django 5.2.18 on 2026-10-06 14:46

import apps.clinical.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('appointments', '0001_initial'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('chief_complaint', models.CharField(max_length=255, verbose_name='presenting complaint')),
                ('history', models.TextField(blank=True, verbose_name='history')),
                ('examination', models.TextField(blank=True, verbose_name='examination findings')),
                ('bp_systolic', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(40), django.core.validators.MaxValueValidator(300)], verbose_name='BP systolic')),
                ('bp_diastolic', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(200)], verbose_name='BP diastolic')),
                ('pulse', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(250)], verbose_name='pulse (bpm)')),
                ('temperature_c', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(45)], verbose_name='temperature (°C)')),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0.5), django.core.validators.MaxValueValidator(400)], verbose_name='weight (kg)')),
                ('height_cm', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(250)], verbose_name='height (cm)')),
                ('spo2', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(50), django.core.validators.MaxValueValidator(100)], verbose_name='SpO₂ (%)')),
                ('blood_sugar', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(900)], verbose_name='blood sugar (mg/dL)')),
                ('diagnosis', models.CharField(blank=True, max_length=255)),
                ('plan', models.TextField(blank=True, verbose_name='advice / plan')),
                ('follow_up_date', models.DateField(blank=True, help_text='When the patient should come back. Drives follow-up reminders.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visits', to='appointments.appointment')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='accounts.clinic')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visits', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='patients.patient')),
            ],
            options={
                'ordering': ['-visit_date'],
            },
        ),
        migrations.CreateModel(
            name='PrescriptionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine', models.CharField(help_text='e.g. "Tab. Amlodipine 5mg"', max_length=200)),
                ('dose', models.CharField(blank=True, help_text='e.g. "1 tablet"', max_length=100)),
                ('frequency', models.CharField(blank=True, help_text='e.g. "Twice daily (1+0+1)"', max_length=100)),
                ('duration', models.CharField(blank=True, help_text='e.g. "5 days"', max_length=100)),
                ('instructions', models.CharField(blank=True, help_text='e.g. "After meals"', max_length=255)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescription_items', to='clinical.visit')),
            ],
            options={
                'ordering': ['order', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='LabResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(help_text='e.g. "HbA1c", "CBC", "Chest X-ray"', max_length=200)),
                ('result_date', models.DateField(default=django.utils.timezone.localdate)),
                ('result_text', models.TextField(blank=True, verbose_name='result / values')),
                ('is_abnormal', models.BooleanField(default=False, verbose_name='abnormal result')),
                ('file', models.FileField(blank=True, help_text='PDF or photo of the report (optional)', upload_to=apps.clinical.models.lab_upload_path, validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png'])])),
                ('original_filename', models.CharField(blank=True, editable=False, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_results', to='accounts.clinic')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_results', to='patients.patient')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('visit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_results', to='clinical.visit')),
            ],
            options={
                'ordering': ['-result_date', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='visit',
            index=models.Index(fields=['clinic', 'follow_up_date'], name='clinical_vi_clinic__c7059e_idx'),
        ),
        migrations.AddIndex(
            model_name='visit',
            index=models.Index(fields=['patient', '-visit_date'], name='clinical_vi_patient_2c6701_idx'),
        ),
    ]
