# Generated by Django 5.2.18 on 2026-10-07 07:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='temperature_c',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(45)], verbose_name='temperature (°C)'),
        ),
    ]
