# Generated by Django 5.2.18 on 2026-10-06 14:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mrn', models.CharField(help_text='Medical record number, unique within the clinic', max_length=20, verbose_name='MR number')),
                ('full_name', models.CharField(max_length=150)),
                ('guardian_name', models.CharField(blank=True, max_length=150, verbose_name='father / husband name')),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('dob_is_estimated', models.BooleanField(default=False, help_text='Date of birth was worked out from an age the patient gave.')),
                ('phone', models.CharField(help_text='Mobile number', max_length=30)),
                ('whatsapp_phone', models.CharField(blank=True, help_text='Only if different from the mobile number', max_length=30, verbose_name='WhatsApp number')),
                ('whatsapp_number', models.CharField(blank=True, editable=False, max_length=20)),
                ('reminders_opt_in', models.BooleanField(default=True, help_text='Patient agreed to receive appointment and follow-up reminders.', verbose_name='agrees to WhatsApp reminders')),
                ('address', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('blood_group', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3)),
                ('allergies', models.TextField(blank=True, help_text='Drug or food allergies. Shown in red on every screen.')),
                ('chronic_conditions', models.TextField(blank=True, help_text='e.g. Diabetes type 2, Hypertension')),
                ('notes', models.TextField(blank=True, help_text='Non-clinical notes, e.g. preferred language', verbose_name='front-desk notes')),
                ('is_archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patients', to='accounts.clinic')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['full_name'],
                'indexes': [models.Index(fields=['clinic', 'full_name'], name='patients_pa_clinic__f1cf8d_idx'), models.Index(fields=['clinic', 'phone'], name='patients_pa_clinic__c795cb_idx')],
                'constraints': [models.UniqueConstraint(fields=('clinic', 'mrn'), name='unique_mrn_per_clinic')],
            },
        ),
    ]
