# Generated by Django 5.2.18 on 2026-10-07 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='phone',
            field=models.CharField(blank=True, help_text='Leave empty if the patient has no mobile', max_length=30, verbose_name='mobile number'),
        ),
    ]
