# Generated by Django 5.2.18 on 2026-10-06 14:46

import apps.appointments.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_at', models.DateTimeField()),
                ('duration_minutes', models.PositiveSmallIntegerField(default=15)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('confirmed', 'Confirmed by patient'), ('reschedule', 'Wants another time'), ('arrived', 'Arrived / waiting'), ('completed', 'Seen'), ('no_show', 'Did not come'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('confirm_token', models.CharField(default=apps.appointments.models.generate_confirm_token, editable=False, max_length=64, unique=True)),
                ('patient_responded_at', models.DateTimeField(blank=True, null=True)),
                ('patient_note', models.CharField(blank=True, help_text='Message left by the patient', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='accounts.clinic')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('doctor', models.ForeignKey(blank=True, help_text="Leave empty for 'any available doctor'", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='patients.patient')),
            ],
            options={
                'ordering': ['scheduled_at'],
                'indexes': [models.Index(fields=['clinic', 'scheduled_at'], name='appointment_clinic__a48055_idx'), models.Index(fields=['clinic', 'status'], name='appointment_clinic__02f124_idx')],
            },
        ),
    ]
